<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T04_rincian_model extends CI_Model
{

    public $table = 't04_rincian';
    public $id = 'idrincian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idrincian, ta.tahun_ajaran, sklh.nama as sekolah, concat(kls.kelas, " - ", kls.sub_kelas) as kelas');
        $this->datatables->from('t04_rincian r');
		if (isset($_POST['idrincian']) && $_POST['idrincian'] != '') { $this->datatables->like('idrincian', $_POST['idrincian']); }
		if (isset($_POST['tahun_ajaran']) && $_POST['tahun_ajaran'] != '') { $this->datatables->like('tahun_ajaran', $_POST['tahun_ajaran']); }
		if (isset($_POST['sekolah']) && $_POST['sekolah'] != '') { $this->datatables->like('sekolah', $_POST['sekolah']); }
		if (isset($_POST['kelas']) && $_POST['kelas'] != '') { $this->datatables->like('kelas', $_POST['kelas']); }
        //add this line for join
        //$this->datatables->join('table2', 't04_rincian.field = table2.field');
        $this->datatables->join('t01_tahunajaran ta', 'ta.idtahunajaran = r.tahun_ajaran');
        $this->datatables->join('t00_sekolah sklh', 'sklh.idsekolah = r.sekolah');
        $this->datatables->join('t02_kelas kls', 'kls.idkelas = r.kelas');
        //$this->datatables->add_column('action', anchor(site_url('t04_rincian/update/$1'),'Ubah')." | ".anchor(site_url('t04_rincian/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idrincian');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t04_rincian/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t04_rincian/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'idrincian');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idrincian', $q);
		$this->db->or_like('tahun_ajaran', $q);
		$this->db->or_like('sekolah', $q);
		$this->db->or_like('kelas', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idrincian', $q);
		$this->db->or_like('tahun_ajaran', $q);
		$this->db->or_like('sekolah', $q);
		$this->db->or_like('kelas', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T04_rincian_model.php */
/* Location: ./application/models/T04_rincian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-09 00:33:19 */
/* http://harviacode.com */
