<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T01_tahunajaran_model extends CI_Model
{

    public $table = 't01_tahunajaran';
    public $id = 'idtahunajaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idtahunajaran,tahun_ajaran');
        $this->datatables->from('t01_tahunajaran');
		if (isset($_POST['idtahunajaran']) && $_POST['idtahunajaran'] != '') { $this->datatables->like('idtahunajaran', $_POST['idtahunajaran']); }
		if (isset($_POST['tahun_ajaran']) && $_POST['tahun_ajaran'] != '') { $this->datatables->like('tahun_ajaran', $_POST['tahun_ajaran']); }
        //add this line for join
        //$this->datatables->join('table2', 't01_tahunajaran.field = table2.field');
        //$this->datatables->add_column('action', anchor(site_url('t01_tahunajaran/update/$1'),'Ubah')." | ".anchor(site_url('t01_tahunajaran/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idtahunajaran');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t01_tahunajaran/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t01_tahunajaran/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'idtahunajaran');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtahunajaran', $q);
		$this->db->or_like('tahun_ajaran', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtahunajaran', $q);
		$this->db->or_like('tahun_ajaran', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T01_tahunajaran_model.php */
/* Location: ./application/models/T01_tahunajaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-08 12:30:04 */
/* http://harviacode.com */