<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T88_menus_model extends CI_Model
{

    public $table = 't88_menus';
    public $id = 'idmenus';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idmenus,menus,kode');
        $this->datatables->from('t88_menus');
		if (isset($_POST['idmenus']) && $_POST['idmenus'] != '') { $this->datatables->like('idmenus', $_POST['idmenus']); }
		if (isset($_POST['menus']) && $_POST['menus'] != '') { $this->datatables->like('menus', $_POST['menus']); }
		if (isset($_POST['kode']) && $_POST['kode'] != '') { $this->datatables->like('kode', $_POST['kode']); }
        //add this line for join
        //$this->datatables->join('table2', 't88_menus.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t88_menus/update/$1'),'Ubah')." | ".anchor(site_url('t88_menus/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idmenus');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idmenus', $q);
		$this->db->or_like('menus', $q);
		$this->db->or_like('kode', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idmenus', $q);
		$this->db->or_like('menus', $q);
		$this->db->or_like('kode', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // get data by modul name
    function getByModulName($modulName)
    {
        $this->db->where('kode', $modulName);
        return $this->db->get($this->table)->row();
    }

}

/* End of file T88_menus_model.php */
/* Location: ./application/models/T88_menus_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-13 11:16:36 */
/* http://harviacode.com */
