<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T02_kelas_model extends CI_Model
{

    public $table = 't02_kelas';
    public $id = 'idkelas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idkelas,sekolah.nama as sekolah,kelas,sub_kelas');
        $this->datatables->from('t02_kelas kelas');
		if (isset($_POST['idkelas']) && $_POST['idkelas'] != '') { $this->datatables->like('idkelas', $_POST['idkelas']); }
		if (isset($_POST['sekolah']) && $_POST['sekolah'] != '') { $this->datatables->like('sekolah.nama', $_POST['sekolah']); }
		if (isset($_POST['kelas']) && $_POST['kelas'] != '') { $this->datatables->like('kelas', $_POST['kelas']); }
		if (isset($_POST['sub_kelas']) && $_POST['sub_kelas'] != '') { $this->datatables->like('sub_kelas', $_POST['sub_kelas']); }
        //add this line for join
        //$this->datatables->join('table2', 't02_kelas.field = table2.field');
        $this->datatables->join('t00_sekolah sekolah', 'kelas.sekolah = sekolah.idsekolah');
        //$this->datatables->add_column('action', anchor(site_url('t02_kelas/update/$1'),'Ubah')." | ".anchor(site_url('t02_kelas/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idkelas');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t02_kelas/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t02_kelas/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'idkelas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idkelas', $q);
		$this->db->or_like('sekolah', $q);
		$this->db->or_like('kelas', $q);
		$this->db->or_like('sub_kelas', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idkelas', $q);
		$this->db->or_like('sekolah', $q);
		$this->db->or_like('kelas', $q);
		$this->db->or_like('sub_kelas', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T02_kelas_model.php */
/* Location: ./application/models/T02_kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-08 23:23:44 */
/* http://harviacode.com */
