<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T03_tagihan_model extends CI_Model
{

    public $table = 't03_tagihan';
    public $id = 'idtagihan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idtagihan,nama');
        $this->datatables->from('t03_tagihan');
		if (isset($_POST['idtagihan']) && $_POST['idtagihan'] != '') { $this->datatables->like('idtagihan', $_POST['idtagihan']); }
		if (isset($_POST['nama']) && $_POST['nama'] != '') { $this->datatables->like('nama', $_POST['nama']); }
        //add this line for join
        //$this->datatables->join('table2', 't03_tagihan.field = table2.field');
        //$this->datatables->add_column('action', anchor(site_url('t03_tagihan/update/$1'),'Ubah')." | ".anchor(site_url('t03_tagihan/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idtagihan');
        $action = "";
        $hakAkses = $this->session->userdata('hakAkses'.substr($this->uri->segment(1), 4));
        if ($hakAkses['ubah']) {
            $action = anchor(site_url('t03_tagihan/update/$1'),'Ubah');
            if ($hakAkses['hapus']) {
                $action .= " | ";
            }
        }
        if ($hakAkses['hapus']) {
            $action .= anchor(site_url('t03_tagihan/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"');
        }
        $this->datatables->add_column('action', $action, 'idtagihan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtagihan', $q);
		$this->db->or_like('nama', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtagihan', $q);
		$this->db->or_like('nama', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T03_tagihan_model.php */
/* Location: ./application/models/T03_tagihan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-09 00:06:57 */
/* http://harviacode.com */