<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T01_tahunajaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T01_tahunajaran_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');        
		$this->load->model('t89_users_menus/T89_users_menus_model');
    }

    public function index()
    {
        // $this->load->view('t01_tahunajaran/t01_tahunajaran_list');
        $data['hakAkses'] = $this->T89_users_menus_model->getHakAkses(substr($this->uri->segment(1), 4));
        $this->session->set_userdata('hakAkses'.substr($this->uri->segment(1), 4), $data['hakAkses']);
        $data['_view'] = 't01_tahunajaran/t01_tahunajaran_list';
        $data['_caption'] = 'Tahunajaran';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T01_tahunajaran_model->json();
    }

    public function read($id)
    {
        $row = $this->T01_tahunajaran_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idtahunajaran' => $row->idtahunajaran,
				'tahun_ajaran' => $row->tahun_ajaran,
	    	);
            $this->load->view('t01_tahunajaran/t01_tahunajaran_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_tahunajaran'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t01_tahunajaran/create_action'),
		    'idtahunajaran' => set_value('idtahunajaran'),
		    'tahun_ajaran' => set_value('tahun_ajaran'),
		);
        // $this->load->view('t01_tahunajaran/t01_tahunajaran_form', $data);
        $data['_view'] = 't01_tahunajaran/t01_tahunajaran_form';
        $data['_caption'] = 'Tahunajaran';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'tahun_ajaran' => $this->input->post('tahun_ajaran',TRUE),
	    	);
            $this->T01_tahunajaran_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t01_tahunajaran'));
        }
    }

    public function update($id)
    {
        $row = $this->T01_tahunajaran_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t01_tahunajaran/update_action'),
				'idtahunajaran' => set_value('idtahunajaran', $row->idtahunajaran),
				'tahun_ajaran' => set_value('tahun_ajaran', $row->tahun_ajaran),
	    	);
            // $this->load->view('t01_tahunajaran/t01_tahunajaran_form', $data);
            $data['_view'] = 't01_tahunajaran/t01_tahunajaran_form';
            $data['_caption'] = 'Tahunajaran';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_tahunajaran'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idtahunajaran', TRUE));
        } else {
            $data = array(
				'tahun_ajaran' => $this->input->post('tahun_ajaran',TRUE),
	    	);
            $this->T01_tahunajaran_model->update($this->input->post('idtahunajaran', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t01_tahunajaran'));
        }
    }

    public function delete($id)
    {
        $row = $this->T01_tahunajaran_model->get_by_id($id);
        if ($row) {
            $this->T01_tahunajaran_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t01_tahunajaran'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t01_tahunajaran'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('tahun_ajaran', 'tahun ajaran', 'trim|required');
		$this->form_validation->set_rules('idtahunajaran', 'idtahunajaran', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T01_tahunajaran.php */
/* Location: ./application/controllers/T01_tahunajaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-08 12:30:04 */
/* http://harviacode.com */